//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Furnitura4Coursed.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        public int TovarID { get; set; }
        public string TovarName { get; set; }
        public int TovarManufacturer { get; set; }
        public int TovarQuantityInStock { get; set; }
        public decimal TovarDiscountAmount { get; set; }
        public decimal TovarCost { get; set; }
        public string TovarPhoto { get; set; }
        public string TovarDescription { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
    }
}
